project:
  type: website
  output-dir: _site

website:
  title: "HR CroStat Dash"
  navbar:
    left:
      - href: index.qmd
        text: Naslovnica
      - href: BDP.qmd
        text: Gospodarski rast
      - href: Inflacija.qmd
        text: Inflacija
      - href: Demografija i trziste rada.qmd
        text: Tržište rada
      - href: Fiskalna pozicija i dug.qmd
        text: Fiskalna pozicija i dug
      - href: Platna bilanca.qmd
        text: Platna bilanca
      - href: Okolisni indikatori.qmd
        text: Okoliš

format:
  html:
    theme: cosmo
    toc: true
lang: hr
