name: Render and Publish

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup R (with RSPM binaries)
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "PUT_R_VERSION_HERE"   # npr. "4.4.1" prema renv.lock
          use-public-rspm: true

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: System libs for source builds
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libcurl4-openssl-dev libxml2-dev

      - name: Restore renv
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render site
        run: quarto render

      - name: Publish to GitHub Pages (gh-pages)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
